import datetime
from time import sleep
print("****Efficient Study Tracker****")
myfile = open("Data.txt","rt")
contents = myfile.read()
myfile.close()
print(contents)
a=float(input("Enter your total target study time(hrs): "))
b=float(input("Enter the time you studied(hrs): "))
c=float(input("Enter the time you studied(min): "))
eff=round(((60*b+c)/(60*a))*100,2)
comm=input("Input any Comments: ")
outfile = open("Data.txt","a")
date=datetime.datetime.now()
outfile.write(date.strftime("%d-%m-%Y")+"\t|\t"+str(eff)+"%"+"\t|\t" + comm + "\n")
outfile.close()
myfile = open("Data.txt","rt")
contents = myfile.read()
myfile.close()
print(contents)
print("Closing in 5 seconds... ")
sleep(5)
exit()
